api_platform:
    title: AR 24 Test Case API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    exception_to_status:
        'App\Infrastructure\Ar24\Http\Client\Exception\ApiException': 500
        'RuntimeException': 500
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
